#!/usr/bin/env bash
# KitLuy OS image — build entrypoint.
#
#   build-image.sh --profile store-hub|pi-terminal [--channel internal]
#                  [--enrollment-url URL] [--stage-only] [--out DIR]
#
# STATUS: SCAFFOLDED-EXECUTABLE. The configuration resolution, profile
# composition, gate enforcement and overlay staging below RUN and are tested
# (test/build-gates.test.sh). The final image assembly step — writing the
# dm-verity system partition, the encrypted data partition and the A/B slot
# table onto a real Raspberry Pi OS base — is NOT implemented, because it
# cannot be done honestly while the base-image pin, the signing key and the
# secure-element SKU are unresolved owner values.
#
# The build therefore always produces a STAGED ROOT (a real, inspectable
# filesystem tree) and refuses to claim it produced a flashable image. That
# refusal is the point: a build that emitted an unsigned .img here would be
# indistinguishable from a releasable artifact.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

PROFILE=""
CHANNEL_OVERRIDE=""
ENROLLMENT_URL_OVERRIDE=""
OUT_DIR=""
STAGE_ONLY="no"

usage() {
  cat >&2 <<'EOF'
Usage: build-image.sh --profile <store-hub|pi-terminal> [options]

Options:
  --profile <name>          Image profile to build (required).
  --channel <name>          Release channel: internal|pilot|stable (default: config).
  --enrollment-url <url>    Cloud device-registry base URL for this environment.
  --out <dir>               Output directory (default: build/out/<profile>).
  --stage-only              Stage the root filesystem and stop. Currently the
                            only supported terminal state; see header.
  -h, --help                Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)         PROFILE="${2:-}"; shift 2 ;;
    --channel)         CHANNEL_OVERRIDE="${2:-}"; shift 2 ;;
    --enrollment-url)  ENROLLMENT_URL_OVERRIDE="${2:-}"; shift 2 ;;
    --out)             OUT_DIR="${2:-}"; shift 2 ;;
    --stage-only)      STAGE_ONLY="yes"; shift ;;
    -h|--help)         usage; exit 0 ;;
    *)                 usage; die "unknown argument: $1" ;;
  esac
done

assert_known_profile "$PROFILE"

# --- Resolve configuration --------------------------------------------------
load_config "${KITLUY_OS_IMAGE_ROOT}/config/image.conf"
load_config "${KITLUY_OS_IMAGE_ROOT}/config/profiles/${PROFILE}.conf"

[[ -n "$CHANNEL_OVERRIDE" ]] && KITLUY_RELEASE_CHANNEL="$CHANNEL_OVERRIDE"
[[ -n "$ENROLLMENT_URL_OVERRIDE" ]] && KITLUY_ENROLLMENT_BASE_URL="$ENROLLMENT_URL_OVERRIDE"
OUT_DIR="${OUT_DIR:-${KITLUY_OS_IMAGE_ROOT}/out/${PROFILE}}"

log "profile=${PROFILE} class=${KITLUY_PROFILE_DEVICE_CLASS} channel=${KITLUY_RELEASE_CHANNEL}"

# --- Gates ------------------------------------------------------------------
# Channel gate first: it is the one that decides whether this build is allowed
# to exist at all.
assert_channel_buildable \
  "$KITLUY_RELEASE_CHANNEL" \
  "$KITLUY_IMAGE_SIGNING_KEY_REF" \
  "$KITLUY_SECURE_ELEMENT_MODEL"

BASE_PINNED="yes"
if ! assert_base_pinned "$KITLUY_BASE_OS_RELEASE" "$KITLUY_BASE_OS_IMAGE_SHA256"; then
  BASE_PINNED="no"
  warn "base OS is UNPINNED (KITLUY_BASE_OS_RELEASE / KITLUY_BASE_OS_IMAGE_SHA256 unresolved)."
  warn "the staged root is reproducible; the resulting IMAGE would not be. Flashable output stays blocked."
fi

assert_no_secrets_in_overlay "${KITLUY_OS_IMAGE_ROOT}/overlay"

# --- Stage the root filesystem ----------------------------------------------
STAGE_ROOT="${OUT_DIR}/rootfs"
rm -rf "$OUT_DIR"
mkdir -p "$STAGE_ROOT"

stage_overlay "${KITLUY_OS_IMAGE_ROOT}/overlay/base" "$STAGE_ROOT"
stage_overlay "${KITLUY_OS_IMAGE_ROOT}/overlay/${PROFILE}" "$STAGE_ROOT"

# --- Emit the resolved, non-secret device configuration ---------------------
# This is the only build-time value injection. It carries an environment
# endpoint, a profile and a channel — no credential, no per-device value, no
# Tenant/Store/Location. Assignment is delivered after enrollment, never baked.
install -d "${STAGE_ROOT}/etc/kitluy"
cat > "${STAGE_ROOT}/etc/kitluy/image.env" <<EOF
# GENERATED BY build-image.sh — do not edit on the device.
# Zero-secret by construction: nothing here authenticates anything.
KITLUY_IMAGE_NAME=${KITLUY_IMAGE_NAME}
KITLUY_IMAGE_SCHEMA_VERSION=${KITLUY_IMAGE_SCHEMA_VERSION}
KITLUY_IMAGE_VERSION=${KITLUY_IMAGE_VERSION}
KITLUY_PROFILE=${KITLUY_PROFILE}
KITLUY_DEVICE_CLASS=${KITLUY_PROFILE_DEVICE_CLASS}
KITLUY_RELEASE_CHANNEL=${KITLUY_RELEASE_CHANNEL}
KITLUY_ENROLLMENT_BASE_URL=${KITLUY_ENROLLMENT_BASE_URL}
KITLUY_ENVIRONMENT=${KITLUY_ENVIRONMENT}
KITLUY_DEFAULT_TIMEZONE=${KITLUY_DEFAULT_TIMEZONE}
KITLUY_DEFAULT_LOCALES=${KITLUY_DEFAULT_LOCALES}
KITLUY_BASE_PINNED=${BASE_PINNED}
EOF

# --- Profile composition ----------------------------------------------------
# shellcheck source=profiles/base.sh
source "${SCRIPT_DIR}/profiles/base.sh"
kitluy_profile_base_compose "$STAGE_ROOT"

# shellcheck disable=SC1090
source "${SCRIPT_DIR}/profiles/${PROFILE}.sh"
"kitluy_profile_$(printf '%s' "$PROFILE" | tr '-' '_')_compose" "$STAGE_ROOT"

# --- Manifest ---------------------------------------------------------------
# Release-metadata shape matches manifest v1 (kitluy_releases.release_artifacts):
# digest algorithm sha256, signature algorithm ed25519. `signature` is
# deliberately absent, not empty — an empty signature field reads as "signed
# with nothing", and this artifact is not signed.
MANIFEST="${OUT_DIR}/release-manifest.json"
ROOTFS_DIGEST="$(cd "$STAGE_ROOT" && find . -type f -print0 | LC_ALL=C sort -z \
  | xargs -0 sha256sum 2>/dev/null | sha256sum | cut -d' ' -f1)"

cat > "$MANIFEST" <<EOF
{
  "manifestVersion": ${KITLUY_RELEASE_MANIFEST_VERSION},
  "imageName": "${KITLUY_IMAGE_NAME}",
  "profile": "${KITLUY_PROFILE}",
  "deviceClass": "${KITLUY_PROFILE_DEVICE_CLASS}",
  "releaseChannel": "${KITLUY_RELEASE_CHANNEL}",
  "digestAlgorithm": "${KITLUY_RELEASE_DIGEST_ALGORITHM}",
  "signatureAlgorithm": "${KITLUY_RELEASE_SIGNATURE_ALGORITHM}",
  "stagedRootDigest": "${ROOTFS_DIGEST}",
  "basePinned": ${BASE_PINNED/no/false},
  "signed": false,
  "flashableImage": false,
  "status": "STAGED-UNSIGNED"
}
EOF
# `basePinned` above resolves to true only when BASE_PINNED was "yes".
sed -i 's/"basePinned": yes/"basePinned": true/' "$MANIFEST"

log "staged root:      ${STAGE_ROOT}"
log "release manifest: ${MANIFEST}"

if [[ "$STAGE_ONLY" == "yes" ]]; then
  log "stage-only requested — stopping here."
  exit 0
fi

# --- Image assembly (BLOCKED) -----------------------------------------------
cat >&2 <<EOF
[kitluy-os-image] BLOCKED-NOT-EXECUTED: flashable image assembly.
  dm-verity system partition, encrypted data partition and A/B slot assembly
  are not implemented. They require, and do not have:
    - KITLUY_BASE_OS_RELEASE / KITLUY_BASE_OS_IMAGE_SHA256 (base pin)
    - KITLUY_IMAGE_SIGNING_KEY_REF   (BLK-005 implementation)
    - KITLUY_SECURE_ELEMENT_MODEL    (production BOM)
  The staged root above is real and inspectable. No .img was produced, and
  none is claimed. Re-run with --stage-only to make this the intended result.
EOF
exit 3
