#!/usr/bin/env bash
# KitLuy OS image — PI_TERMINAL profile composition.
#
# Adds the kiosk runtime, Hub discovery and peripheral setup.
#
# The terminal PROFILE (T1..T4) is NOT decided here. One image serves every
# terminal profile; the profile arrives as governed configuration after
# cloud-authorised assignment. Baking T1 into an image would make the image the
# source of assignment truth, which the provisioning chain forbids.

kitluy_profile_pi_terminal_compose() {
  local root="${1:-}"
  [[ -n "$root" ]] || die "pi-terminal compose: no stage root"
  local unit_dir="${root}/etc/systemd/system"
  install -d "$unit_dir"

  # Unprivileged kiosk user. The POS client never runs as root.
  install -d "${root}/etc/sysusers.d"
  cat > "${root}/etc/sysusers.d/60-kitluy-terminal.conf" <<EOF
u ${KITLUY_KIOSK_USER} - "KitLuy terminal kiosk runtime" /var/lib/kitluy/terminal
EOF
  install -d "${root}/var/lib/kitluy/terminal"

  # The kiosk client REQUIRES the enrollment agent: a terminal with no identity
  # has nothing to present to a Hub, and a kiosk that starts anyway would show
  # an operator a POS surface that cannot transact.
  # Canonical terminal units (session = enabled, client = governed release,
  # defined but NOT enabled) come from the shared overlay.
  kitluy_install_overlay "$root" "${KITLUY_OS_IMAGE_ROOT}/rpi-image-gen/layer/kitluy-pi-terminal.rootfs-overlay"

  cat > "${root}/etc/kitluy/terminal.env" <<EOF
# GENERATED BY build-image.sh — non-secret terminal runtime configuration.
# NOTE: no terminal profile, Tenant, Digital Store, Location or Hub endpoint
# appears here. All of those are delivered by governed configuration after
# assignment, and a terminal that has not been assigned has none of them.
KITLUY_KIOSK_RUNTIME=${KITLUY_KIOSK_RUNTIME}
KITLUY_KIOSK_USER=${KITLUY_KIOSK_USER}
KITLUY_MDNS_SERVICE=${KITLUY_MDNS_SERVICE}
KITLUY_HUB_MANUAL_ENDPOINT_ALLOWED=${KITLUY_HUB_MANUAL_ENDPOINT_ALLOWED}
KITLUY_PERIPHERAL_SUPPORT=${KITLUY_PERIPHERAL_SUPPORT}
EOF

  log "pi-terminal composition applied (kiosk ${KITLUY_KIOSK_RUNTIME}, discovery ${KITLUY_MDNS_SERVICE})"
}
