/**
 * How the enrollment agent resolves its configuration FROM THE IMAGE.
 *
 * This file exists because of a defect that no test could see: the agent read
 * `KITLUY_FLEET_BASE_URL` from `/etc/kitluy/fleet.env`, while every build path
 * writes `KITLUY_ENROLLMENT_BASE_URL` into `/etc/kitluy/image.env`. Neither the
 * variable nor the file was ever produced, so the endpoint was unresolvable on
 * a real device no matter how the image was built — and `evaluateBootstrap`
 * had no test at all, so nothing contradicted the agent's own header.
 *
 * The assertions below are therefore deliberately about the CONTRACT BETWEEN
 * TWO COMPONENTS — the key name and the file the image actually ships — not
 * about the agent's internal shape.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { IDENTITY_FILE_NAME } from "../src/adapters/device-identity-store.js";
import { evaluateBootstrap } from "../src/bin/enrollment-bootstrap.js";
import type { EnrollmentClient } from "../src/enrollment.js";

let root: string;
let etcRoot: string;
let ticketPath: string;

/** The exact bytes `build-image.sh` writes, comments included. */
function writeImageEnv(lines: readonly string[]): void {
  mkdirSync(join(etcRoot, "kitluy"), { recursive: true });
  writeFileSync(
    join(etcRoot, "kitluy", "image.env"),
    ["# GENERATED BY build-image.sh — do not edit on the device.", ...lines, ""].join("\n"),
  );
}

/** A default route, so the agent gets past NETWORK_WAIT. */
function writeProcRoute(): string {
  const procRoot = join(root, "proc");
  mkdirSync(join(procRoot, "net"), { recursive: true });
  writeFileSync(
    join(procRoot, "net", "route"),
    "Iface\tDestination\tGateway\tFlags\neth0\t00000000\t0102A8C0\t0003\n",
  );
  return procRoot;
}

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "kitluy-enrollment-config-"));
  etcRoot = join(root, "etc");
  ticketPath = join(root, "ticket");
  writeFileSync(ticketPath, "reference=TICKET-001\nsecret=not-a-real-secret\n");
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("enrollment agent image configuration", () => {
  it("reads the endpoint the image ACTUALLY ships", async () => {
    writeImageEnv([
      "KITLUY_ENROLLMENT_BASE_URL=https://registry.example",
      "KITLUY_ENVIRONMENT=pilot",
    ]);
    const client: EnrollmentClient = {
      enroll: () => Promise.resolve({ kind: "enrolled", deviceRecordId: "dev-1" }),
      heartbeat: () => Promise.resolve({ kind: "refused", code: "X", retryable: true }),
      pollAssignment: () => Promise.resolve({ kind: "unassigned" }),
    };
    // The endpoint is consumed when building the real transport, so its
    // resolution is observed through the branch it controls: with a resolvable
    // endpoint the agent proceeds to enrol rather than reporting it missing.
    const { result } = await evaluateBootstrap({
      identityDir: identityDirWithIdentity(),
      ticketPath,
      procRoot: writeProcRoute(),
      etcRoot,
      client,
    });
    expect(result.phase).toBe("ENROLLED_UNASSIGNED");
  });

  it("reports the endpoint MISSING when the image shipped an empty value", async () => {
    // `KITLUY_ENROLLMENT_BASE_URL=` is what a build with no environment URL
    // writes. Empty is absent, not an endpoint whose address is "".
    writeImageEnv(["KITLUY_ENROLLMENT_BASE_URL=", "KITLUY_ENVIRONMENT=development"]);
    const { result } = await evaluateBootstrap({
      identityDir: identityDirWithIdentity(),
      ticketPath,
      procRoot: writeProcRoute(),
      etcRoot,
    });
    expect(result.phase).toBe("UNENROLLED");
    expect(result.detail).toContain("no enrollment endpoint is configured");
  });

  it("reports the endpoint MISSING when there is no image.env at all", async () => {
    const { result } = await evaluateBootstrap({
      identityDir: identityDirWithIdentity(),
      ticketPath,
      procRoot: writeProcRoute(),
      etcRoot,
    });
    expect(result.phase).toBe("UNENROLLED");
    expect(result.detail).toContain("no enrollment endpoint is configured");
  });

  it("carries the image version from the same file into the reported state", async () => {
    writeImageEnv(["KITLUY_IMAGE_VERSION=9.9.9-test", "KITLUY_ENROLLMENT_BASE_URL="]);
    const { state } = await evaluateBootstrap({
      identityDir: identityDirWithIdentity(),
      ticketPath,
      procRoot: writeProcRoute(),
      etcRoot,
    });
    expect(state.imageVersion).toBe("9.9.9-test");
  });

  it("enrols as the class the image declares, never a guessed one", async () => {
    writeImageEnv([
      "KITLUY_DEVICE_CLASS=store_hub",
      "KITLUY_ENROLLMENT_BASE_URL=https://registry.example",
    ]);
    let seenClass = "";
    const client: EnrollmentClient = {
      enroll: (input) => {
        seenClass = input.deviceClass;
        return Promise.resolve({ kind: "enrolled", deviceRecordId: "dev-1" });
      },
      heartbeat: () => Promise.resolve({ kind: "refused", code: "X", retryable: true }),
      pollAssignment: () => Promise.resolve({ kind: "unassigned" }),
    };
    await evaluateBootstrap({
      identityDir: identityDirWithIdentity(),
      ticketPath,
      procRoot: writeProcRoute(),
      etcRoot,
      client,
    });
    // A Hub that enrolled as a terminal would only be discovered at Store
    // pairing, long after the mistake.
    expect(seenClass).toBe("store_hub");
  });

  it("defaults the class to terminal when the image declares none", async () => {
    writeImageEnv(["KITLUY_ENROLLMENT_BASE_URL=https://registry.example"]);
    let seenClass = "";
    const client: EnrollmentClient = {
      enroll: (input) => {
        seenClass = input.deviceClass;
        return Promise.resolve({ kind: "enrolled", deviceRecordId: "dev-1" });
      },
      heartbeat: () => Promise.resolve({ kind: "refused", code: "X", retryable: true }),
      pollAssignment: () => Promise.resolve({ kind: "unassigned" }),
    };
    await evaluateBootstrap({
      identityDir: identityDirWithIdentity(),
      ticketPath,
      procRoot: writeProcRoute(),
      etcRoot,
      client,
    });
    expect(seenClass).toBe("terminal");
  });
});

/**
 * A complete identity on disk, so the agent reaches the configuration branch
 * rather than stopping at IDENTITY_INITIALIZING.
 */
function identityDirWithIdentity(): string {
  const dir = join(root, "identity");
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, IDENTITY_FILE_NAME),
    JSON.stringify({
      publicKeyPem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA\n-----END PUBLIC KEY-----\n",
      privateKeyHandle: join(dir, "device-key.pem"),
      createdAt: "2026-01-01T00:00:00.000Z",
      hardwareSignals: {},
      complete: true,
    }),
  );
  return dir;
}
