/**
 * How the operational-TLS unit resolves its endpoint FROM THE IMAGE.
 *
 * The same defect class as `enrollment-bootstrap-config.test.ts`, one unit
 * later in the lifecycle. `bin/operational-tls.ts` read `KITLUY_REGISTRATION_URL`
 * and appended `/v1/operational-certificate` to it. That key names the CLOUD
 * REGISTRATION ROUTE as a FULL url, on a different service — the image layer
 * says in so many words that the fleet service "does not serve this route", and
 * that a device assembling one endpoint from the other "would POST to a host
 * answering 404". So the certificate request went to
 * `<registration-route>/v1/operational-certificate`, and a 404 is
 * indistinguishable to the device from a governed refusal.
 *
 * Nothing contradicted it because `bin/operational-tls.ts` exported nothing and
 * took no `etcRoot`, so the `image.env` -> client composition never executed off
 * the device. The existing operational-TLS tests all inject a `baseUrl`
 * directly, which is exactly the value in question, so they cannot see which
 * key produced it.
 *
 * The assertions below are therefore about the CONTRACT BETWEEN TWO COMPONENTS
 * — which key the image ships, and which service serves the route — not about
 * the unit's internal shape.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { OPERATIONAL_CERTIFICATE_PATH } from "../src/adapters/http-operational-certificate-client.js";
import { readOperationalBaseUrl } from "../src/bin/operational-tls.js";

/** The fleet service: serves /v1/device-enrollment, /v1/hub-pairing AND this route. */
const FLEET_BASE_URL = "http://192.168.1.50:8080";

/** A DIFFERENT service. Present in every real image.env, and never this route. */
const REGISTRATION_URL = "https://example-ref.supabase.co/functions/v1/device-registration";

let root: string;
let etcRoot: string;

/** The exact keys every build path writes into /etc/kitluy/image.env. */
function writeImageEnv(lines: readonly string[]): void {
  mkdirSync(join(etcRoot, "kitluy"), { recursive: true });
  writeFileSync(
    join(etcRoot, "kitluy", "image.env"),
    ["# GENERATED BY the kitluy-hub-base layer — do not edit on the device.", ...lines, ""].join(
      "\n",
    ),
  );
}

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "kitluy-opcert-endpoint-"));
  etcRoot = join(root, "etc");
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("operational certificate endpoint resolution", () => {
  it("resolves the FLEET SERVICE origin, not the registration route", () => {
    writeImageEnv([
      `KITLUY_ENROLLMENT_BASE_URL=${FLEET_BASE_URL}`,
      `KITLUY_REGISTRATION_URL=${REGISTRATION_URL}`,
    ]);

    expect(readOperationalBaseUrl(etcRoot)).toBe(FLEET_BASE_URL);
  });

  /**
   * THE REGRESSION ASSERTION. Reinstating the original key makes the composed
   * url `<registration-route>/v1/operational-certificate`, and this fails
   * naming the service that does not serve the route.
   */
  it("never composes the certificate url on the registration service", () => {
    writeImageEnv([
      `KITLUY_ENROLLMENT_BASE_URL=${FLEET_BASE_URL}`,
      `KITLUY_REGISTRATION_URL=${REGISTRATION_URL}`,
    ]);

    const composed = `${readOperationalBaseUrl(etcRoot) ?? ""}${OPERATIONAL_CERTIFICATE_PATH}`;

    expect(composed).toBe(`${FLEET_BASE_URL}/v1/operational-certificate`);
    expect(composed).not.toContain("device-registration");
    expect(composed).not.toContain(REGISTRATION_URL);
  });

  /**
   * A registration url alone must NOT satisfy this unit. Before the fix it did,
   * and the device spent its retries against a host that never serves the route.
   */
  it("stays unresolved when only the registration route is configured", () => {
    writeImageEnv([`KITLUY_ENROLLMENT_BASE_URL=`, `KITLUY_REGISTRATION_URL=${REGISTRATION_URL}`]);

    expect(readOperationalBaseUrl(etcRoot)).toBeUndefined();
  });

  it("is unresolved when image.env carries no fleet endpoint at all", () => {
    writeImageEnv([`KITLUY_ENVIRONMENT=development`]);

    expect(readOperationalBaseUrl(etcRoot)).toBeUndefined();
  });

  it("is unresolved when image.env does not exist", () => {
    expect(readOperationalBaseUrl(etcRoot)).toBeUndefined();
  });
});
