#!/usr/bin/env bash
# KitLuy OS image — STORE_HUB profile composition.
#
# Adds what only a Hub has: NVMe-backed local PostgreSQL, the Hub agent serving
# the LAN /edge/v1 API, sync services and mDNS advertisement.
#
# The Hub does not become local Store authority here. It becomes authority only
# after assignment and activation succeed — which is cloud-governed and arrives
# as delivered configuration, not as an image property.

kitluy_profile_store_hub_compose() {
  local root="${1:-}"
  [[ -n "$root" ]] || die "store-hub compose: no stage root"
  local unit_dir="${root}/etc/systemd/system"
  install -d "$unit_dir" "${root}/var/lib/kitluy/hub"

  # Local PostgreSQL data directory lives on the encrypted data partition.
  install -d -m 0700 "${root}/var/lib/kitluy/hub/postgresql"

  cat > "${unit_dir}/kitluy-hub-agent.service" <<'EOF'
[Unit]
# GOVERNED RELEASE UNIT — defined here, NOT enabled. The Hub agent binary is
# delivered by the governed release system; enabling it in the golden image
# would restart-loop against an absent executable.
Description=KitLuy Store Hub agent (LAN /edge/v1 API, sync, local authority)
After=network-online.target postgresql.service kitluy-enrollment-agent.service
Wants=network-online.target
Requires=postgresql.service

[Service]
Type=simple
EnvironmentFile=/etc/kitluy/image.env
EnvironmentFile=/etc/kitluy/hub.env
ExecStart=/usr/lib/kitluy/hub-agent
Restart=always
RestartSec=10s
ProtectSystem=strict
ProtectHome=yes
NoNewPrivileges=yes
ReadWritePaths=/var/lib/kitluy

[Install]
WantedBy=multi-user.target
EOF

  # mDNS advertisement. Terminals listen for exactly this service name; it is
  # locked by the bootstrap contract and must not be renamed here.
  cat > "${unit_dir}/kitluy-hub-discovery.service" <<'EOF'
[Unit]
# GOVERNED RELEASE UNIT — defined here, NOT enabled (see above).
Description=KitLuy Store Hub LAN discovery advertisement
After=kitluy-hub-agent.service avahi-daemon.service
Wants=avahi-daemon.service
Requires=kitluy-hub-agent.service

[Service]
Type=simple
EnvironmentFile=/etc/kitluy/image.env
EnvironmentFile=/etc/kitluy/hub.env
ExecStart=/usr/lib/kitluy/hub-discovery-advertise
Restart=always
RestartSec=15s
NoNewPrivileges=yes

[Install]
WantedBy=multi-user.target
EOF

  # Non-secret Hub runtime configuration. The local database DSN is created on
  # the device at activation and is NOT written here — a DSN baked into an
  # image is a credential in an image.
  # Names are the ones the agent READS (kitluy-hub-agent/src/main.ts). The old
  # `KITLUY_LAN_*` prefix matched nothing in code, so every value written here
  # was inert and the agent silently used its own defaults.
  #
  # No bind host: `createEdgeTlsServer` refuses `0.0.0.0` (FORBIDDEN_BINDS), and
  # the real interface address is not knowable at build time.
  cat > "${root}/etc/kitluy/hub.env" <<EOF
# GENERATED BY build-image.sh — non-secret Hub runtime configuration.
HUB_LAN_PORT=${KITLUY_LAN_PORT}
HUB_LAN_TLS_MIN_VERSION=${KITLUY_LAN_TLS_MIN_VERSION}
HUB_MDNS_SERVICE=${KITLUY_MDNS_SERVICE}
HUB_LOCAL_DATABASE=${KITLUY_LOCAL_DATABASE}
HUB_LOCAL_DATABASE_MAJOR_VERSION=${KITLUY_LOCAL_DATABASE_MAJOR_VERSION}
HUB_NVME_REQUIRED=${KITLUY_NVME_REQUIRED}
EOF

  log "store-hub composition applied (LAN port ${KITLUY_LAN_PORT}, mDNS ${KITLUY_MDNS_SERVICE})"
}
